"""Add new database

Revision ID: d8c6d63a4ca0
Revises: 19dc0aae1cfa
Create Date: 2024-11-09 21:32:01.384477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c6d63a4ca0'
down_revision = '19dc0aae1cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('id_kelas', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id'], name='fk_siswa_kelas'),
    sa.PrimaryKeyConstraint('nisn'),
    sa.UniqueConstraint('nisn'),
    sa.UniqueConstraint('username')
    )
    op.create_table('kehadiran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn_siswa', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nisn_siswa'], ['siswa.nisn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    op.drop_table('siswa')
    op.drop_table('kelas')
    op.drop_table('admin')
    # ### end Alembic commands ###
